Numpy
Numpy is a fundamental library of scientific computing in python. it provides support for arrays and matrices., along with a collection of mathematics function to operate on these data structures . In this lesson , we will be focusing on the basics of numpy and array vectorized operations.

In [11]:
!pip install numpy 


[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: C:\Users\Manu\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [12]:
%pip install numpy 
import numpy as np 
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))

Note: you may need to restart the kernel to use updated packages.
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


You should consider upgrading via the 'c:\Users\Manu\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [13]:
import numpy as np 
# 1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [14]:
#2D Array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
arr2.reshape(1,6)

[[1 2 3]
 [4 5 6]]
(2, 3)


array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
##Numpy vectorized operations
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[11 22 33 44 55 66]
[ -9 -18 -27 -36 -45 -54]
[ 10  40  90 160 250 360]
[0.1 0.1 0.1 0.1 0.1 0.1]


In [24]:
##universal functions
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))   
print(np.divide(arr1,arr2))
print(np.sqrt(arr1))

[11 22 33 44 55 66]
[ -9 -18 -27 -36 -45 -54]
[ 10  40  90 160 250 360]
[0.1 0.1 0.1 0.1 0.1 0.1]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [25]:
##slicing and indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])  # Accessing element at row 0, column
print(arr[1,:])  # Accessing entire row 1
print(arr[:,2])  # Accessing entire column 2
print(arr[1:3, 0:2])  # Accessing a subarray (rows 1-2, columns 0-1)
print(arr[0:2, 1:3])  # Accessing a subarray (rows 0-1, columns 1-2)
print(arr[1, 1:3])  # Accessing a specific row and a range of columns
print(arr[0:2, 0:2])  # Accessing a subarray (rows 0-1, columns 0-1)

2
[4 5 6]
[3 6 9]
[[4 5]
 [7 8]]
[[2 3]
 [5 6]]
[5 6]
[[1 2]
 [4 5]]


In [26]:
##modifying arrays
arr[0,0]=10
print(arr)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [27]:
### statistical concepts - normalization
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr - mean) / std_dev 
print("Original Array:\n", arr)
print("Mean:", mean)
print("Standard Deviation:", std_dev)
print("Normalized Array:\n", normalized_arr)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean: 5.0
Standard Deviation: 2.581988897471611
Normalized Array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [30]:
##logical operations
arr1 = np.array([1, 2, 3, 4, 5])
arr1>1
arr1[arr1>1]  # Accessing elements greater than 1


array([2, 3, 4, 5])